### ISSUE TITLE
Presets are always saved/loaded with lowercase names

### ISSUE THREAD

**Issue by 1darky** [HaodongMo/ArcCW#100]
No matter what you type into preset nane, it will appear in list with all small letters

Also taskmaster reported that he cant save more than 12 presets   not tested not confirmed

**Comment by Fesiug** [comment]
Files cannot be saved with uppercase characters.

**Comment by Fesiug** [comment]
![image](https://user-images.githubusercontent.com/40924091/150179030-29b547d7-1fd8-4374-bb31-66ae4513d8fe.png)
