### ISSUE TITLE
A variety of FoV related discrepancies

### ISSUE THREAD

**Issue by littlebabyman** [HaodongMo/ArcCW#106]
Scoped in, the viewmodel FoV is all over the place, expecting 16:9.
![20220222181529_1](https://user-images.githubusercontent.com/3816236/155178031-d260f4b7-d38d-4b98-92f6-90abff56cba2.jpg)
![20220222181354_1](https://user-images.githubusercontent.com/3816236/155177844-3f210db4-0d3f-4cce-8813-d65e5c6ae900.jpg)
![20220222181442_1](https://user-images.githubusercontent.com/3816236/155178006-e9fb99b3-ae1f-495a-85b6-fd8859e504bb.jpg)

Crosshair scales incorrectly with screen width, rather than the FoV.
![20220222182341_1](https://user-images.githubusercontent.com/3816236/155179396-b0e70d94-ded0-4ef8-a7ed-e3c364645dfa.jpg)
![20220222182119_1](https://user-images.githubusercontent.com/3816236/155179417-85b37d99-3bfe-4b73-9ba3-6b97f48cf3ac.jpg)
![20220222182233_1](https://user-images.githubusercontent.com/3816236/155179427-aa3b7f02-fab8-495d-9b7a-2ec5de80c5e2.jpg)

Viewmodel FoV also should be based on vertical FoV for consistency's sake, also seen above, and likely also relating to the first issue.
![20220222182855_1](https://user-images.githubusercontent.com/3816236/155180067-57c0ea41-57c8-40a0-bfa7-8fad6411a473.jpg)
![20220222183020_1](https://user-images.githubusercontent.com/3816236/155180082-0a6e4e72-e2b2-4a75-9de5-e338bf43b4ff.jpg)
![20220222182931_1](https://user-images.githubusercontent.com/3816236/155180090-b94a2e78-968c-4e09-ac00-0d1b76861714.jpg)

It also causes the muzzle effects to appear too far into or out of the weapon.
![20220222193343_1](https://user-images.githubusercontent.com/3816236/155186988-f5fa330d-e62f-472f-bf39-d03bc34a8b5e.jpg)
![20220222193258_1](https://user-images.githubusercontent.com/3816236/155187004-d60f0eeb-69f2-42b6-8390-0b1757cdb22f.jpg)
![20220222193423_1](https://user-images.githubusercontent.com/3816236/155187024-27f7687d-46ea-44d7-8369-c5bf877a5c75.jpg)

**Comment by Fesiug** [comment]
Fixed!
