### ISSUE TITLE
Options Set For Laser/Flashlight Attachments Don't Save

### ISSUE THREAD

**Issue by dottiekh** [HaodongMo/ArcCW#112]
First off I want to apologize if this has already been mentioned/discussed since I wasn't able to find anything about it when I looked.

Certain attachments with settings for them (such as Flashlights with High, Eco, Off settings) don't save between map changes or game launches even if the lock is set. The attachment will always reset to unlocked and it's default setting. 

![image](https://user-images.githubusercontent.com/34873184/163701657-14beb46c-ee54-427c-ae3a-35e4c380a5de.png)

**Comment by 1darky** [comment]
Lock is for switch bind, you wont be able to toggle that att if lock pressed
Recently flashlight bind toggle was added, enable it in Binds settings

**Comment by dottiekh** [comment]
WOW that explains a lot lol. Thanks.

Then, would it be possible for the saving of these attachment settings to be a feature?

**Comment by 1darky** [comment]
Don't think so, team is working on new base

**Comment by TheOnly8Z** [comment]
This has actually been implemented since preset rework.
