### ISSUE TITLE
Penetrating through the very very very thick wall

### ISSUE THREAD

**Issue by neve3more** [HaodongMo/ArcCW#116]
Currently bullets can penetrate *very* thick walls, even entire buildings.

We should probably limit the penetrating power, if possible.

Map: **gm_goldencity_v2_day**

https://youtu.be/ZsnSb90_CJU

**Comment by TheOnly8Z** [comment]
Addressed in 7b2c42d2ec07cc2b243509eb991ece90d85d5ef0. related to glass penetration multiplier being very low.
