### ISSUE TITLE
NPC damage mult doesn't work, Player mult changes both

### ISSUE THREAD

**Issue by DELNEMESIS** [HaodongMo/ArcCW#126]
When NPC Holding a ArcCW Weapon, NPC Deals a lots of damage(NPC Damage 1). so i set the npc damage to 0.1 but it has a same damage. so i set the Normal(Player) Damage to 0.1 and the NPC damage has been reduced. but also player's damage has been reduced too.

**Comment by TheOnly8Z** [comment]
Cannot replicate - presumed fixed.

Do note Damage multiplier is applied to all damage, not just players.
