### ISSUE TITLE
Problems with the C-menu (I am writing from a translator)

### ISSUE THREAD

**Issue by beerzavrs** [HaodongMo/ArcCW#128]
I have no body kits in the C-menu, what should I do????
On a normal day, I just go to my favorite server, there is nothing in my C-menu here.
(It's in solitary)
![Снимок экрана 2022-08-11 164217](https://user-images.githubusercontent.com/111056995/184121511-f05887de-e2a3-42ec-82f7-79abbc4d3185.png)
.

**Comment by dar-su** [comment]
Your favourite server has disbled attachments

**Comment by beerzavrs** [comment]
But I have the same problem on other servers

**Comment by beerzavrs** [comment]
I FOUND THE SOLUTION!!! JUST SHOULD DISABLE THIS SETTING!!!
![Снимок экрана 2022-08-11 174908](https://user-images.githubusercontent.com/111056995/184126975-47b7332d-5e3b-4586-85e9-16692b132980.png)
!

**Comment by Fesiug** [comment]
i cant read that
