### ISSUE TITLE
arccw causes errors with x64 temp build

### ISSUE THREAD

**Issue by BadaBingBR** [HaodongMo/ArcCW#144]
[arccw] addons/arccw/lua/arccw/server/sv_net.lua:3: attempt to call field 'AddNetworkString' (a nil value)
  1. unknown - addons/arccw/lua/arccw/server/sv_net.lua:3
   2. include - [C]:-1
    3. unknown - addons/arccw/lua/autorun/arccw_autorun.lua:24

happens when loading a map

**Comment by dar-su** [comment]
Use old x64 for now, they changed something related to file.Find in new gmod build
