### ISSUE TITLE
Recent updates don't let inspect anims properly play (Urban Coalition weapons)

### ISSUE THREAD

**Issue by BadaBingBR** [HaodongMo/ArcCW#147]
Both tested with UD and UR, the inspect anims don't play fully now, they cut right back into idle.

**Comment by GermanPlasma** [comment]
I cannot exactly explain why, but if I change the lines

48 `local noinspect = ArcCW.ConVars["noinspect"]`

55 `noinspect = noinspect or ArcCW.ConVars["noinspect"]`

in sh_customize back to the way it was handled before:

48 `local noinspect = GetConVar("arccw_noinspect")`

55 `noinspect = noinspect or GetConVar("arccw_noinspect")`

Then the inspect animations work again. Nothing else I tried seemed to work, especially not playing around with the disable inspect animations button. Those two lines, without changing anything else, do the trick for me, yet I don't understand exactly why this is the case.

**Comment by TheOnly8Z** [comment]
`arccw_noinspect` is a client convar - no idea how it was even working before.
