### ISSUE TITLE
No penetration or ricochet on multiplayer servers

### ISSUE THREAD

**Issue by GermanPlasma** [HaodongMo/ArcCW#149]
When on a multiplayer server (tested on peer-to-peer as well as local server), weapons cannot penetrate and bullets don't seem to ricochet at all.

When switching back to singleplayer, both features work perfectly fine. Even amplifying the value changes nothing on multiplayer servers, whereas it lets me shoot through houses in singleplayer.

 Tested with all needed addons and no other mods installed.

**Comment by TheOnly8Z** [comment]
Please check if `arccw_enable_penetration` and `arccw_enable_ricochet` convars are set.

**Comment by GermanPlasma** [comment]
Definitely both enabled! Just retested as well. No matter the surface, no matter the thickness, no penetration to be seen.

**Comment by TheOnly8Z** [comment]
Replicated on a dedicated server.

**Comment by TheOnly8Z** [comment]
Looks like it was actually fully functioning, but weren't showing clientside cause it was disabled for some reason.
