### ISSUE TITLE
NPCs creating errors when shooting

### ISSUE THREAD

**Issue by KVT2349** [HaodongMo/ArcCW#151]
[[ArcCW] Arctic's Customizable Weapons (Base)] lua/weapons/arccw_base/sh_attach.lua:684: attempt to call method 'GetViewModel' (a nil value)
1. unknown - lua/weapons/arccw_base/sh_attach.lua:684 (x8)

This happens when an NPC shoots. i know it's a small issue but it's been bugging me since last week. I didn't install any addons from then, it just happened

**Comment by TheOnly8Z** [comment]
Should be fixed. Reopen if issue persists on git version.
