### ISSUE TITLE
vang in AttPosMods does not work. :nopog:

### ISSUE THREAD

**Issue by GamerBarney** [HaodongMo/ArcCW#44]

**Comment by GamerBarney** [comment]
![20201208090301_1](https://user-images.githubusercontent.com/68207899/101500666-66c1ed80-3934-11eb-97b3-bb1ffd7831e0.jpg)
![Screenshot (717)](https://user-images.githubusercontent.com/68207899/101500681-6cb7ce80-3934-11eb-8a3d-9a8b7ac422ab.png)

**Comment by TheOnly8Z** [comment]
added :^)
