### ISSUE TITLE
weapon jamming.

### ISSUE THREAD

**Issue by Heyter** [HaodongMo/ArcCW#56]
Are you planning to do weapon jamming?

**Comment by Fesiug** [comment]
There is already weapon jamming??

**Comment by Heyter** [comment]
> There is already weapon jamming??

What do you mean? Where?

**Comment by Fesiug** [comment]
Look for it cunt

**Comment by Heyter** [comment]
> Look for it, cunt

heat != jamming.

**Comment by Fesiug** [comment]
Then what do you mean

**Comment by Heyter** [comment]
> Then what do you mean

look at TFA.

**Comment by Fesiug** [comment]
write it yourself then. should be very easy, with changing of the values of the heat system and sumn like

SWEP.Hook_Think = function(wep)
if util.SharedRandom("jam", 0, 1) < self:GetHeat() then
self:overheat??()
end
end

**Comment by Fesiug** [comment]
should be able to figure it out yourself

**Comment by Heyter** [comment]
> write it yourself then. should be very easy, with changing of the values of the heat system and sumn like
> 
> SWEP.Hook_Think = function(wep)
> if util.SharedRandom("jam", 0, 1) < self:GetHeat() then
> self:overheat??()
> end
> end

As a rule, I don't like modifying someone else's code. Because then it is more difficult to update to the latest version.

**Comment by Fesiug** [comment]
> > write it yourself then. should be very easy, with changing of the values of the heat system and sumn like
> > 
> > SWEP.Hook_Think = function(wep)
> > if util.SharedRandom("jam", 0, 1) < self:GetHeat() then
> > self:overheat??()
> > end
> > end
> 
> As a rule, I don't like modifying someone else's code. Because then it is more difficult to update to the latest version.

put it in your custom weapon 😪

**Comment by Heyter** [comment]
> > > write it yourself then. should be very easy, with changing of the values of the heat system and sumn like
> > > SWEP.Hook_Think = function(wep)
> > > if util.SharedRandom("jam", 0, 1) < self:GetHeat() then
> > > self:overheat??()
> > > end
> > > end
> > 
> > 
> > As a rule, I don't like modifying someone else's code. Because then it is more difficult to update to the latest version.
> 
> put it in your custom weapon 😪

I'm not a swep developer.

**Comment by Fesiug** [comment]
> > > > write it yourself then. should be very easy, with changing of the values of the heat system and sumn like
> > > > SWEP.Hook_Think = function(wep)
> > > > if util.SharedRandom("jam", 0, 1) < self:GetHeat() then
> > > > self:overheat??()
> > > > end
> > > > end
> > > 
> > > 
> > > As a rule, I don't like modifying someone else's code. Because then it is more difficult to update to the latest version.
> > 
> > put it in your custom weapon 😪
> 
> I'm not a swep developer.

then what are you doing here
