### ISSUE TITLE
Holstering causes animation issues with HL2 weapons

### ISSUE THREAD

**Issue by thejaviertc** [HaodongMo/ArcCW#64]
I have seen this when you are doing faster moves with the weapon (like pick a weapon and changing to another).
When you do that, the physics gun starts shacking and this error appears in server console spamming a lot (client console is clean):

![image](https://user-images.githubusercontent.com/45662206/117546058-c7ab3a00-b028-11eb-85f8-b826b905d0f4.png)

I'm adding a video for better understanding: https://user-images.githubusercontent.com/45662206/117546459-d4309200-b02a-11eb-9bf4-342f4b2fb29c.mp4

It only stops when you click somewhere with the physics gun: https://user-images.githubusercontent.com/45662206/117546605-8405ff80-b02b-11eb-9b99-a0d0c3813944.mp4

I'm using ArcCW Gunsmith Offensive.

**Comment by TheOnly8Z** [comment]
Verified. Seems like ``SetPlaybackRate`` isn't changing the speed as it should, but that alone isn't the problem.

**Comment by TheOnly8Z** [comment]
Prediction, man.
