### ISSUE TITLE
Shotgun-type weapons produce no blood decals

### ISSUE THREAD

**Issue by BadaBingBR** [HaodongMo/ArcCW#66]
Pistols, rifles, snipers and SMG's all work fine, but shotguns produce no blood decals on a wall or anything behind a npc when shoot.

**Comment by TheOnly8Z** [comment]
Verified.

**Comment by TheOnly8Z** [comment]
Fixed - engine quirk where damage with only DMG_BUCKSHOT makes no decals. By default, all damage that is only DMG_BUCKSHOT gets DMG_BULLET added to it (like HL2 shotgun) now.
