### ISSUE TITLE
Spawned Weapon with weapon:Spawn() wont have random Attachments on

### ISSUE THREAD

**Issue by rAiZeNXD** [HaodongMo/ArcCW#72]
As the Title says it spawns Weapon but without Attachmetns

**Comment by Auditormadness9** [comment]
Same issue but with spawning the weapon for the player.

**Comment by rAiZeNXD** [comment]
> 
> 
> Same issue but with spawning the weapon for the player.

Use NPCSetup or something like this

**Comment by Auditormadness9** [comment]
> > Same issue but with spawning the weapon for the player.
> 
> Use NPCSetup or something like this

I checked the source code and it's what was being used in the first place. It's weird.
